[WIP][11.0][MIG] account_operation_rule > account_reconcile_rule
OCA/account-reconcile pull request #209
Opened 2018-04-23 13:02 UTC by grindtildeath

Todo :
 - [ ] Fix Javascript
 - [ ] Check readme

2018-04-26 07:05 UTC, simahawk requested changes

2018-04-26 07:05 UTC, simahawk commented on account_reconcile_rule/__manifest__.py
> +# © 2014-2016 Camptocamp SA
`Copyright`

2018-04-26 07:05 UTC, simahawk commented on account_reconcile_rule/__manifest__.py
> + 'website': 'http://www.camptocamp.com',
https://github.com/OCA/account-reconcile

2018-04-26 07:05 UTC, simahawk commented on account_reconcile_rule/__manifest__.py
> + 'installable': True,
you can drop these flags

2018-04-26 07:05 UTC, simahawk commented on account_reconcile_rule/i18n/account_statement_operation_rule.pot
> +# Translation of Odoo Server.
remove POT

2018-04-26 07:05 UTC, simahawk commented on account_reconcile_rule/model/__init__.py
> +
empty line not needed

2018-04-26 07:05 UTC, simahawk commented on account_reconcile_rule/model/account_reconcile_rule.py
> +        string='Operations'
trailing comma

2018-04-26 07:05 UTC, simahawk commented on account_reconcile_rule/model/account_reconcile_rule.py
> +        amount_min = self.amount_min
you don't need these vars

2018-04-26 07:05 UTC, simahawk commented on account_reconcile_rule/model/account_reconcile_rule.py
> +        """ Check if the multi-currency rule can be applied
no wrapping space

2018-04-26 07:05 UTC, simahawk commented on account_reconcile_rule/model/account_reconcile_rule.py
> +        """ Returns True if a rule applies to a group of statement_line +
`"""Check if a rule applies to a group of statement_line + move lines.`

2018-04-26 07:05 UTC, simahawk commented on account_reconcile_rule/model/account_reconcile_rule.py
> +        """ Find the rules that apply to a statement line and
`"""Find rules to apply to given statement line and move lines.`

2018-04-26 07:05 UTC, simahawk commented on account_reconcile_rule/model/account_reconcile_rule.py
> +        """ Find the rule for the current reconciliation and returns the
`"""Find reconcile models for given statement and move lines.`
explain "how" in the extra lines.

2018-04-26 07:05 UTC, simahawk commented on account_reconcile_rule/static/src/js/account_widgets.js
> +
```javascript\
/*
Explain what you do here 
*/`
```

2018-04-26 07:05 UTC, simahawk commented on account_reconcile_rule/static/src/js/account_widgets.js
> +         * Click on add_line link if preset button have been clicked
???

2018-04-26 07:05 UTC, simahawk commented on account_reconcile_rule/tests/common.py
> +
remove some useless empty line

2018-04-26 07:05 UTC, simahawk commented on account_reconcile_rule/tests/common.py
> +        super(AccountReconciliationModelTestCase, cls).setUpClass()
you can call `super()` w/out args

2018-04-26 08:03 UTC, guewen approved these changes
Code LGTM (only some commented lines to remove), tested on runbot, works great. Thanks!

2018-04-26 08:03 UTC, guewen commented on account_reconcile_rule/static/src/js/account_widgets.js
> +//        }
I guess the commented lines can be removed

2018-04-26 10:11 UTC, simahawk approved these changes

2018-04-30 10:14 UTC, tschanzt reviewed
Some of the Headers have the wrong Daterange in it for the licence. But otherwise :+1:

2019-03-01 21:07 UTC, grindtildeath commented
@tschanzt Can you approve or add suggestions to correct the date range so we can get this merged ? :pray: :wink:

2019-03-21 08:34 UTC, simahawk commented
@tschanzt ping

2019-03-21 15:02 UTC, tschanzt approved these changes

2019-06-26 14:53 UTC, benbrich commented
@fclementic2c how about an merge here? Everythings seems allright from over here. Thx!

2019-07-04 13:24 UTC, benbrich commented
@fclementic2c sorry for poking you on this one, I have learned from @OSevangelist that you are more into funtional stuff. @tafaRU or @jbeficent could you please be so kind and merge this one? Thanks!

2019-07-23 13:54 UTC, pedrobaeza commented
/ocabot merge

2019-07-23 14:40 UTC, closed without merging