[12.0][MIG] account_move_reconcile_helper
OCA/account-reconcile pull request #246
Opened 2019-03-28 12:21 UTC by Abranes

Standard migration

2019-03-28 15:28 UTC, Abranes commented
I don't know why runbot fail, [account_balance_line](https://github.com/OCA/account-financial-tools/tree/12.0/account_balance_line) is migrated to 12.0.

Can anyone help me?

2019-03-28 17:41 UTC, pedrobaeza commented
You have to add `oca_dependencies.txt` file in root for adding extra OCA repositories for dependencies.

2019-03-29 14:58 UTC, Abranes commented
Oh! Sorry, I miss that! Now it's done and :green_apple:!

2019-03-29 15:38 UTC, fuentes73 approved these changes

2019-04-20 13:58 UTC, tbaden requested changes
thanks for your work 👍 
just a minor change (see below)
and please squash your commits.

2019-04-20 13:58 UTC, tbaden commented on account_move_reconcile_helper/views/account_move_line.xml
> +    <record model="ir.ui.view" id="account_move_line_tree_view">
aesthetic change: use original id

> In the case where an inherited view has a name which does not follow the guidelines set above, prefer naming the inherited view after the original over using a name which follows the guidelines. This eases looking up the original view and other inheritance if they all have the same name.

not approve relevant

2019-04-20 13:58 UTC, tbaden commented on account_move_reconcile_helper/__manifest__.py
> +    'demo': [
if you dont use this tag, just delete it

2019-04-23 06:21 UTC, benwillig approved these changes
LGTM. Thanks for the migration

2019-06-13 14:38 UTC, Abranes commented
@tbaden Squash and minor changes done!

2019-07-12 07:43 UTC, CasVissers-360ERP approved these changes
LGTM!

2019-08-07 17:33 UTC, Jortolsa-S73 approved these changes

2019-08-08 08:38 UTC, Abranes commented
@pedrobaeza Can you review this?

2019-08-08 09:09 UTC, pedrobaeza commented
Merging blindly as it seems there are enough reviewers.

/ocabot merge

2019-08-08 09:34 UTC, closed without merging