[13.0][mig] base_transaction_id
OCA/account-reconcile pull request #325
Opened 2020-07-27 12:40 UTC by captivea-dcr

2021-04-05 14:50 UTC, alexey-pelykh commented
@captivea-dcr Please squash last two commits

2021-04-05 14:51 UTC, alexey-pelykh requested changes

2021-04-05 14:51 UTC, alexey-pelykh commented on base_transaction_id/__manifest__.py
> +    "version": "13.0.2.0.0",
It should be 13.0.1.0.0

2022-06-26 12:16 UTC, closed without merging

2023-06-30 12:19 UTC, NL66278 commented on base_transaction_id/models/invoice.py
> +# Copyright 2019 Camptocamp SA
file should be named account_move.py