[14.0] account_reconciliation_widget: remove payment_id <> false
OCA/account-reconcile pull request #382
Opened 2021-04-21 19:22 UTC by alexis-via

Remove the condition on payment_id <> false in the method _domain_move_lines_for_reconciliation()
because the OCA module account_payment_order doesn't generate account.payment objects.

2021-04-21 22:21 UTC, pedrobaeza reviewed
I have this also on my TODO, but I'm wondering about adding the payment generation support to bank-payment, due to the new invoice states for indicating that is being paid. It's very useful and our customers demand that since a lot.

2021-05-17 12:56 UTC, joao-p-marques requested changes
@alexis-via could you also include a change like https://github.com/OCA/account-reconcile/pull/390/files#diff-00ca0391f0efd17a399a50f2dca6af6f06a32a2456f722c4f3a01b1edcdb4e91R777-L836?

It comes from the original patch by @carlosdauden in https://github.com/OCA/OCB/pull/678

2021-09-04 09:11 UTC, pedrobaeza approved these changes
Let's move with this as we haven't yet performed anything of the payment order refactoring. @joao-p-marques can you update your review?

2021-09-04 09:47 UTC, alexis-via commented
@pedrobaeza Yes, let's move on until we have the payment order refactoring.
I'm working on a big dev for VAT declaration in France, it should be finished in 2-3 weeks I hope (it's almost finished, but the last bits + writing tests take a lot of time according to my experience). Then, I'm OK to work with you on payment order refactoring with the use of account.payment. It would be great to do it before we start porting to v15.

2021-09-04 09:49 UTC, pedrobaeza commented
OK, tell me and we can make a kick-off meeting.

2021-09-04 09:49 UTC, alexis-via commented
@pedrobaeza OK, good idea. I try to finish my FR VAT declaration ASAP.

2021-09-06 07:36 UTC, joao-p-marques reviewed
I still think it would make sense to include the patch from https://github.com/OCA/account-reconcile/pull/390 here, or has that bug been fixed somewhere else?

2021-09-06 07:38 UTC, pedrobaeza commented
Do you mean the `if st_line.company_id.account_bank_reconciliation_start:` part?

2021-09-06 07:39 UTC, pedrobaeza commented
I don't see such part in https://github.com/OCA/OCB/pull/678

2021-09-06 07:45 UTC, joao-p-marques commented
> Do you mean the `if st_line.company_id.account_bank_reconciliation_start:` part?
> 
> I don't see such part in OCA/OCB#678

Yes, sorry, maybe that was not the best reference. That was the original patch for v10, but if you take a look at the ported one to v12 you will see that extra change: https://github.com/OCA/OCB/pull/884

I just did the same in the other PR

2021-09-06 08:42 UTC, pedrobaeza commented
@alexis-via can you please check the comments from my colleague Joao?

2022-07-01 06:56 UTC, alexis-via commented
I added the res.company date field account_bank_reconciliation_start on the settings config page.

2022-07-01 06:59 UTC, pedrobaeza commented
@alexis-via apart from pre-commit fail, if you want that the `account_bank_reconciliation_start` works, you have to move it like in https://github.com/OCA/OCB/pull/884. Can you please do it?

2022-07-01 09:29 UTC, pedrobaeza approved these changes

2022-07-01 09:29 UTC, pedrobaeza commented
Please rebase and fix conflicts

2022-07-01 18:27 UTC, carlosdauden approved these changes
LGTM

2022-07-01 18:28 UTC, pedrobaeza commented
There are conflicts, so a rebase is needed. Please @alexis-via 

Or if you prefer, I can push your commits on top of the branch.

2022-07-06 12:00 UTC, alexis-via commented
Rebased. Almost all the changes/fixes introduced by this PR are now already in origin/14.0. The only change left is the addition of the date field account_bank_reconciliation_start on the accounting config page.

2022-07-06 14:56 UTC, alexis-via commented
/ocabot merge minor

2022-07-06 15:05 UTC, merged

2022-07-06 15:14 UTC, pedrobaeza commented
A change on the commit message/PR title + commit squashing would be advisable, as now the diff doesn't correspond with the message, but thanks anyways for the contribution.

2022-07-06 15:56 UTC, pedrobaeza commented
FW-port it to 15.0 in  #481