Filtered out invoices in canceled state from bank reconcilation
OCA/account-reconcile pull request #451
Opened 2022-03-10 21:27 UTC by tosink

2022-03-10 21:30 UTC, tosink commented
I have reviewed the errors on the 2 failing, it's some errors with your pre-commit and runboat. Nothing to do with the code. It's just one line of code added.

2022-03-11 06:19 UTC, pedrobaeza commented on account_reconciliation_widget/models/reconciliation_widget.py
> +        domain.append(["move_id.state","!=","cancel"])
Respect pre-commit:

```suggestion
        domain.append(["move_id.state", "!=", "cancel"])
```

2022-03-11 06:20 UTC, pedrobaeza requested changes
Anyways, do this in `_domain_move_lines_for_reconciliation`, and only add `posted` entries (draft should be excluded as well).

2022-03-11 11:02 UTC, tosink commented
I think I've passed all the checks now.

2022-03-14 15:04 UTC, tosink commented
Any updates on the merging?

2022-04-14 14:40 UTC, andrewdhastings approved these changes
Looks good to me.

2022-04-14 14:42 UTC, andrewdhastings commented
@pedrobaeza Is there anything preventing this from being merged?

2022-04-14 14:46 UTC, pedrobaeza commented
Please squash commits into one.

2022-04-14 15:02 UTC, andrewdhastings commented
@pedrobaeza Not sure if that worked? Not sure why the travis ci failed, I didn't change anything else.

2022-04-14 15:04 UTC, pedrobaeza commented
The squash is not correct: you have now more commits than before.

2022-04-14 15:05 UTC, pedrobaeza commented
I'm picking the diff myself, so please wait.

2022-04-14 15:08 UTC, andrewdhastings commented
K, sorry, I can make a new branch and submit a fresh merge request if needs be. Sorry, not sure how to retroactively squash commits.

2022-04-14 15:09 UTC, pedrobaeza commented
Pushed the fix in 9f85c3dc4f1492aae75559db45c4ac81efea2abf

2022-04-14 15:09 UTC, closed without merging

2022-04-14 15:11 UTC, pedrobaeza commented
Cherry-picked to v15 at f343ccfa3c09b3b206f49b2735b0f58068302b45

2022-04-14 15:14 UTC, andrewdhastings commented
Perfect thanks! and thanks for adding to v15