[16.0][IMP] account_mass_reconcile: Add 'oldest move line' option on reconc…
OCA/account-reconcile pull request #604
Opened 2023-10-23 14:36 UTC by aritzolea

…ile option

Oldest move line date option is added for write off move date

Additionally, "Most recent move line" and "Oldest move line" are used for choosing the move which is going to get reconciled if more than one is available.

2023-10-24 08:32 UTC, ljsalvatierra-factorlibre requested changes
Please add tests to cover the oldest use case.

Also, i wouldn't change `last_date` to `most_recent_date`.

2023-10-25 08:28 UTC, aritzolea commented
> Please add tests to cover the oldest use case.
> 
> Also, i wouldn't change `last_date` to `most_recent_date`.

Tests have been added

2023-10-25 08:51 UTC, ljsalvatierra-factorlibre approved these changes

2023-10-25 08:53 UTC, AaronHForgeFlow approved these changes
Code review

2023-10-25 09:04 UTC, florian-dacosta approved these changes
LGTM

2023-10-26 08:37 UTC, gerard-vacas approved these changes

2023-10-26 10:04 UTC, AaronHForgeFlow commented
/ocabot merge minor

2023-10-26 10:08 UTC, merged