[16.0][FIX] account_reconcile_oca: Replace invoice_due_date for date_maturity field on reconcile view.
OCA/account-reconcile pull request #658
Opened 2024-05-22 07:38 UTC by SergioBustamanteFL

We change the field display on reconcile views. Instead of showing `invoice_due_date`, we show `date_maturity`. This also add the possibility to order the list by this field (`asc` or `desc`).

2024-05-22 07:46 UTC, etobella commented
Seems logic, but if you do this, remove the field from the python, as it has no longer sense.

Once it is finished, will you port the changes to 17?

2024-05-22 09:38 UTC, SergioBustamanteFL commented
Hi @etobella 
Sorry. Currently I don't have availability to take it to 17

2024-05-22 11:51 UTC, etobella commented
Really? You just need to make a new branch and a cherry-pick.... It takes like 5 minutes in the worst case scenario :thinking:

2024-05-23 08:08 UTC, ValentinVinagre commented
> Really? You just need to make a new branch and a cherry-pick.... It takes like 5 minutes in the worst case scenario 🤔

@etobella ... the worker does not decide, it is the company that does not allow him time. There is also free time, but it is up to the person who decides whether to do it or not. In this case... it is because the person does not want to do this continuity work, so they do not complain if the PSC's do not review their contributions 😄

2024-05-23 08:11 UTC, pedrobaeza commented
I think @liebana should comment about the predisposition of his company to do the full chain of fixes.

2024-05-23 09:12 UTC, aritzolea approved these changes

2024-05-23 09:15 UTC, ValentinVinagre commented
@aritzolea validating in draft? 🤔

2024-05-23 19:35 UTC, etobella commented
@SergioBustamanteFL @factorlibre @aritzolea @liebana 
I believe this module is important to the entire community because it provides the reconciliation functionality to Odoo CE. I developed this module a year ago without expecting anything in return. I know you use it for all your v16 customers, and I appreciate that. Working in open source often involves doing this kind of work without recognition or financial reward. I have been developing most of these kind of changes over the last two years, and I am very happy with that.

In my opinion, asking for the forward port is not unreasonable, and I believe you are capable of handling it, which is why I requested it. Otherwise, I would need to do this work myself, and I want to avoid that. I understand that your customer is not paying for this work, but you are also requesting reviews without offering anything in return and it will not be merged without external reviews. This is a common occurrence in OSS development, and we all deal with it.

My statement is this: It won't be a problem if you don't want to do it, but in that case, you can close the PR because it will not be merged without that commitment.

Any other solution places the burden on others (primarily myself), which it is not fair.

2024-05-24 08:49 UTC, liebana commented
"I think @liebana should comment about the predisposition of his company to do the full chain of fixes."

"the person does not want to do this continuity work, so they do not complain if the PSC's do not review their contributions 😄"

"My statement is this: It won't be a problem if you don't want to do it, but in that case, you can close the PR because it will not be merged without that commitment."


You should be ashamed of your neighborhood bully comments, my friends. A detailed explanation of the motivations to Sergio, a newcomer to the team, would have been more than enough for us to do it without any issues. Moreover, you know me and you are just two clicks away on various platforms to write to me privately, without the need to try to shame or single us out in public. We have only uploaded an improvement, which we consider interesting, to a community module.

But now I'm not concerned about Sergio or us, but about other newcomers to the community. Your comments and attitudes are far from optimal, and I think you should deeply reflect on that.

2024-05-24 09:30 UTC, etobella commented
Firstly, Sergio mentioned, "Sorry. Currently I don't have availability to take it to 17." This likely indicates that "the customer isn't funding this upgrade" or "my boss says I shouldn't do that". While this is a valid reason, as a maintainer, I want to ensure consistency across versions. My focus is maintaining this tool as effectively as possible.

It's important to understand that eventually, migration will be necessary, and it’s more efficient to address it now. Delaying means I'll have to review and port all changes between versions later, which is significantly more work and something I’m unable to undertake at this time.

Regarding the claim of bullying, I believe I was polite and explained the importance of the task. Unfortunately, Sergio didn't respond to my explanation. Please note that I took time away from my usual work to review his PR, provide feedback, and ask relevant questions. I wasn't obligated to do so, and the simplest response would have been silence and let the PR die. Remember, this work is done on a voluntary basis without compensation. Thus, we should appreciate any feedback, whether from a senior developer, junior, or newcomer, as it is given freely and with the intention of improvement.

Lastly, I prefer keeping discussions public for transparency. This way, anyone reviewing the thread later can understand the full context.

I also recommend reading these insightful posts about open-source contributions:

https://snarky.ca/setting-expectations-for-open-source-participation/
https://dhh.dk/2012/rails-is-omakase.html

2024-05-24 09:46 UTC, liebana commented
You are entering again into the spiral of explanations about the motivations and management of an open-source project, which we share. But I repeat that the approach and threats (I won’t merge the improvement or don’t expect a PSC to review your contributions if you don’t do what I say) are not correct.

From our side, the debate ends here.

2024-05-24 09:51 UTC, pedrobaeza commented
OK, so for having things clear, your company are not going to do any forward-port to upper versions, isn't it?

2024-05-24 09:54 UTC, liebana commented
What my company do or not do, is up to us. I don't have to give you any explanation and you don't have any right to ask me about it.

2024-05-24 10:09 UTC, ljsalvatierra-factorlibre commented
> @SergioBustamanteFL @factorlibre @aritzolea @liebana I believe this module is important to the entire community because it provides the reconciliation functionality to Odoo CE. I developed this module a year ago without expecting anything in return. I know you use it for all your v16 customers, and I appreciate that. Working in open source often involves doing this kind of work without recognition or financial reward. I have been developing most of these kind of changes over the last two years, and I am very happy with that.
> 
> In my opinion, asking for the forward port is not unreasonable, and I believe you are capable of handling it, which is why I requested it. Otherwise, I would need to do this work myself, and I want to avoid that. I understand that your customer is not paying for this work, but you are also requesting reviews without offering anything in return and it will not be merged without external reviews. This is a common occurrence in OSS development, and we all deal with it.
> 
> My statement is this: It won't be a problem if you don't want to do it, but in that case, you can close the PR because it will not be merged without that commitment.
> 
> Any other solution places the burden on others (primarily myself), which it is not fair.

I speak only in my name, but this is clearly a threat. You should not use your position to silence contributors as you see fit, this is very sad.

2024-05-24 10:10 UTC, etobella requested changes
Well, he may ask, but it's up to you to respond or not. Ultimately, it's your company and your decision. However, as the maintainer of this module, my responsibility is to ensure the integrity and consistency of all its versions. For this reason, I have marked this PR as not mergeable due to the lack of willingness to port it.

I understand your position, but you should also understand that maintaining consistency between versions is crucial. If the necessary changes take just a couple of minutes and there is reluctance to make them, I cannot in good conscience allow the differences to persist.

2024-05-24 10:38 UTC, etobella commented
@ljsalvatierra-factorlibre where did I silent him? He can answer on this topic at any moment.

I just stated my opinion and it is clearly as valid as his or yours. However, I am the maintainer of this module and I just try to keep it between multiple versions. I know that some companies use only some versions and it is completely legit, however, I am wearing right now the hat of maintainer of this module and I cannot accept differences that takes 5 minutes of work.

Reading again my comment, the only sentence I find that can be problematic is:

> My statement is this: It won't be a problem if you don't want to do it, but in that case, you can close the PR because it will not be merged without that commitment.

I apologize if this came across as a threat; that was not my intention. I was trying to show that his way is valid for him, but he should understand that we cannot accept it inside OCA because it is giving work to other people. Addressing this now takes just five minutes, whereas doing it later could take two hours or more due to the need to review the entire history. Worse, the improvement might be lost if I cannot allocate those hours. This 5 minutes will benefit everyone (even your future you, because probably the feature will be lost). 

If you choose not to make these changes, that's entirely your decision, whether personal or company-based. However, in that case, I think we don't need to continue this discussion.

2024-05-24 10:57 UTC, ValentinVinagre commented
> > @SergioBustamanteFL @factorlibre @aritzolea @liebana I believe this module is important to the entire community because it provides the reconciliation functionality to Odoo CE. I developed this module a year ago without expecting anything in return. I know you use it for all your v16 customers, and I appreciate that. Working in open source often involves doing this kind of work without recognition or financial reward. I have been developing most of these kind of changes over the last two years, and I am very happy with that.
> > In my opinion, asking for the forward port is not unreasonable, and I believe you are capable of handling it, which is why I requested it. Otherwise, I would need to do this work myself, and I want to avoid that. I understand that your customer is not paying for this work, but you are also requesting reviews without offering anything in return and it will not be merged without external reviews. This is a common occurrence in OSS development, and we all deal with it.
> > My statement is this: It won't be a problem if you don't want to do it, but in that case, you can close the PR because it will not be merged without that commitment.
> > Any other solution places the burden on others (primarily myself), which it is not fair.
> 
> I speak only in my name. This is clearly a threat. You should not use your position to silence contributors as you see fit, this is very sad.

In the time you have spent responding to comments and exposing the "bullying" you are suffering... you could have fixed the world.

2024-05-24 11:03 UTC, ljsalvatierra-factorlibre commented
> > > @SergioBustamanteFL @factorlibre @aritzolea @liebana I believe this module is important to the entire community because it provides the reconciliation functionality to Odoo CE. I developed this module a year ago without expecting anything in return. I know you use it for all your v16 customers, and I appreciate that. Working in open source often involves doing this kind of work without recognition or financial reward. I have been developing most of these kind of changes over the last two years, and I am very happy with that.
> > > In my opinion, asking for the forward port is not unreasonable, and I believe you are capable of handling it, which is why I requested it. Otherwise, I would need to do this work myself, and I want to avoid that. I understand that your customer is not paying for this work, but you are also requesting reviews without offering anything in return and it will not be merged without external reviews. This is a common occurrence in OSS development, and we all deal with it.
> > > My statement is this: It won't be a problem if you don't want to do it, but in that case, you can close the PR because it will not be merged without that commitment.
> > > Any other solution places the burden on others (primarily myself), which it is not fair.
> > 
> > 
> > I speak only in my name. This is clearly a threat. You should not use your position to silence contributors as you see fit, this is very sad.
> 
> In the time you have spent responding to comments and exposing the "bullying" you are suffering... you could have fixed the world.

Sure, I should just accept this kind of behaviour and do what I'm told :+1:

2024-05-28 16:09 UTC, vdewulf commented
Hello everyone,

Things are heating up here! It is sad to see these disagreement but it's normal in any open source community to have conflicting point of views.

Here is my personal point of view as Executive Director for the OCA, my goal being to both make sure new contributors are welcome and make sure the work accomplished by older contributors is being respected as well as our rules.

First, thanks to @SergioBustamanteFL for making this PR and improving the reconciliation module, which is a key module inside the OCA ecosystem.

Secondly, I'd like to recall the role of maintainers in our community: "A Maintainer is responsible to ensure the coordination of specific addon modules in order to ensure the quality and consistency of the contributions." (source: https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/oca_module_lifecycle_maintainer_role.rst). In addition, the "PSCs are free to set community and technical direction for their project, and are directly responsible for overseeing releases and the healthy development of their communities." (source: https://odoo-community.org/about/how-we-work)

I believe it is in this perspective that @etobella requested a port of the change to the next version: ensuring consistency of the contributions and asking what he would ask anyone contributing to an OCA module existing in different versions. 

It's a good practice to make your improvements available in the version your company is interested in and on the upper existing versions when they exist. This will benefit many people in the community and you certainly benefited from this good practice when installing and using OCA modules.

The integrator company that pays you to contribute might see that as an additional cost but it's in reality a good investment for the future (your own future customers who will be migrated in the next years to a newer version of this same module). I believe it's something the OCA as a whole should explain more and make some lobby to the companie's CEO who encourage their people to contribute to the OCA.

However, I must say that @etobella did write a strange sentence when telling "My statement is this: It won't be a problem if you don't want to do it, but in that case, you can close the PR because it will not be merged without that commitment."
But he then apologized.

I hope that @SergioBustamanteFL will find the 5 minutes needed to port his improvements to version 17, now that the current OCA way of working is more explicitly stated. This would be very appreciated.

I agree that no one should do what he is told to do just because it's what he's told to. I also believe that people can do things they didn't want to do at first when they see the bigger picture.

I hope this contribution will find his way very soon to the v16 and v17!

2024-05-29 10:53 UTC, etobella approved these changes
Thanks for the change. Works as expected

2024-05-29 10:54 UTC, etobella commented
/ocabot merge patch

2024-05-29 10:59 UTC, merged