[16.0][IMP] account_statement_base: add possibility to navigate from statement lines to the associated journal entry
OCA/account-reconcile pull request #678
Opened 2024-08-05 10:34 UTC by JordiBForgeFlow

Through a button. Adds also the journal entry number as an optional field.

![image](https://github.com/user-attachments/assets/802557f8-b8cf-4940-bfc5-1143bcde6427)

cc @etobella @pedrobaeza @alexis-via

2024-08-05 10:44 UTC, pedrobaeza requested changes

2024-08-05 10:44 UTC, pedrobaeza commented on account_statement_base/models/account_bank_statement_line.py
> +        action = self.env.ref("account.action_move_line_form").sudo().read()[0]
Please use the newer form to do this with `self.env["ir.actions.actions"]._for_xml_id()`

2024-08-05 10:44 UTC, pedrobaeza commented on account_statement_base/models/account_bank_statement_line.py
> +        del action["views"]
You are removing here the possible specific form view. This can have side effects.

2024-08-05 10:44 UTC, pedrobaeza commented on account_statement_base/views/account_bank_statement_line.xml
> +                    string="Open Journal Entry"
I think there shouldn't be string. And please put title for proper screen readers (for blind people) usage.

2024-08-05 10:44 UTC, pedrobaeza commented on account_statement_base/views/account_bank_statement_line.xml
> +
Don't add empty line here.

2024-08-05 10:53 UTC, JordiBForgeFlow commented
@pedrobaeza Thanks. I have attended your review comments

2024-08-05 11:00 UTC, pedrobaeza commented
You should squash by default the commits, as it doesn't add value. We have here in GitHub a differential view of the latest changes already.

2024-08-05 13:02 UTC, JordiBForgeFlow commented
Squashed. 

What I don't like about adding the button is that it shows always. We cannot make it optional, as it happens with normal fields.

2024-08-05 17:49 UTC, pedrobaeza commented
Really? You can't make it invisible AFAIK.

2024-08-14 20:21 UTC, etobella approved these changes
I don't see a problem on leaving the button visible :thinking:

2024-08-14 20:30 UTC, pedrobaeza commented
Sorry, I wrote the reverse sentence: "you can make the button invisible with the `attrs` thing AFAIK". Can you try?

2024-09-23 13:44 UTC, JordiBForgeFlow commented
@pedrobaeza Can we merge this one?

2024-09-23 14:23 UTC, pedrobaeza commented
Please do it invisible when no move present.

2024-09-23 15:27 UTC, JordiBForgeFlow commented
> Please do it invisible when no move present.

I do not understand your suggestion. there's always a move.

2024-09-23 18:27 UTC, pedrobaeza approved these changes
Oh, sorry, my bad.

/ocabot merge minor

2024-09-23 18:32 UTC, merged